name: Seed and deploy
on:
  workflow_dispatch:
  schedule:
  # At 08:00 daily
  - cron: "0 8 * * *"
jobs:
    seed:
        name: Seed and deploy
        runs-on: ubuntu-22.04
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Set up and seed
              run: |
                  npm ci --only=dev
                  npx prisma db seed
              env:
                  CI: true
