name: Seed and deploy
on:
  workflow_dispatch:
  schedule:
  # At 08:00 daily
  - cron: "0 8 * * *"
jobs:
    seed:
        name: Seed and deploy
        runs-on: ubuntu-22.04
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Set up and seed
              run: |
                  npm ci
                  npx prisma db seed
              env:
                  CI: true
                  PRISMA_DB: ${{ secrets.PRISMA_DB }}
            - name: Trigger re-deployment
              uses: fjogeleit/http-request-action@master
              with:
                  url: ${{ secrets.DEPLOY_WEBHOOK }}
                  method: 'POST'
