name: Test
on:
  pull_request:
  push:
    branches: [main]
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_PASSWORD: postgres
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 5s
                    --health-timeout 5s
                    --health-retries 10
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm
            - run: npm ci
            - run: npx tsc --noEmit
            - run: npm run lint
            - run: npm test
